In [2]:
#Numpy

In [3]:
import numpy as np

In [4]:
GKnames=["Kaller","Fradeel","Hayward","Honeyman"]
GKheights=[184,188,191,193]
GKweights=[81,85,103,99]

print(np.array(GKnames))

['Kaller' 'Fradeel' 'Hayward' 'Honeyman']


In [5]:
GKmatrix=[GKnames,GKheights,GKweights]
print(np.array(GKmatrix))

[['Kaller' 'Fradeel' 'Hayward' 'Honeyman']
 ['184' '188' '191' '193']
 ['81' '85' '103' '99']]


In [6]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
import random

In [11]:
print(np.random.randn(3,3))
print(np.random.randint(1,100,(3,3)))

[[-0.46031709  1.05340649  0.90530547]
 [ 1.50250095  1.57723138 -0.89439373]
 [-1.11653016 -1.27510275 -0.41801186]]
[[60 21 86]
 [46 40 83]
 [40 98 68]]


In [12]:
GKheights=np.array(GKheights)

In [13]:
GKheights.max()

np.int64(193)

In [14]:
GKheights.argmax()

np.int64(3)

In [15]:
GKnames[GKheights.argmax()]

'Honeyman'

In [19]:
WcYears=np.arange(1930,2018,4)
WcYears=np.delete(WcYears,(3,4))
print(WcYears)

[1930 1934 1938 1950 1954 1958 1962 1966 1970 1974 1978 1982 1986 1990
 1994 1998 2002 2006 2010 2014]


In [20]:
WCyears=[2002,2006,2010,2014]
WChosts=["Japan/Korea","Germany","South Africa","Brazil"]
WCwinners=["Brazil","Italy","Spain","Germany"]
WCarray=np.array((WCyears,WChosts,WCwinners))
print(WCarray)

[['2002' '2006' '2010' '2014']
 ['Japan/Korea' 'Germany' 'South Africa' 'Brazil']
 ['Brazil' 'Italy' 'Spain' 'Germany']]


In [21]:
WCarray[1,2]

np.str_('South Africa')

In [22]:
WCarray[2,-1]

np.str_('Germany')

In [23]:
WCyears=np.array([1966,1970,1974,1978])
WCtopscorers=np.array(["Eusebio","Muller","Lato","Kempes"])
WCgoals=np.array([9,10,7,6])
WC=np.array((WCyears,WCtopscorers,WCgoals))
print(WC)

[['1966' '1970' '1974' '1978']
 ['Eusebio' 'Muller' 'Lato' 'Kempes']
 ['9' '10' '7' '6']]


In [25]:
print(WCtopscorers[WCgoals.argmax()])

Muller


In [3]:
print(WCgoals.max())

NameError: name 'WCgoals' is not defined

In [2]:
#Pandas 

In [ ]:
import numpy as np
import pandas as pd